# Generated by Django 3.1.2 on 2022-05-24 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('nombre_empresa', models.CharField(max_length=30)),
                ('rut_empresa', models.CharField(max_length=40)),
                ('direccion_empresa', models.CharField(max_length=40)),
                ('administrador_id_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.administrador')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
