# Generated by Django 3.1.2 on 2022-05-24 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('productos', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle Pedido',
                'verbose_name_plural': 'Detalle Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_proveedor', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.administrador')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
