# Generated by Django 3.1.2 on 2022-05-24 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_detallepedido_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id_minuta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('tipo_desayuno', models.CharField(max_length=50)),
                ('tipo_almuerzo', models.CharField(max_length=50)),
                ('tipo_once', models.CharField(max_length=50)),
                ('tipo_cena', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Minuta',
                'verbose_name_plural': 'Minuta',
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('administrador_id_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.administrador')),
                ('detalle_pedido_id_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.detallepedido')),
                ('proveedor_id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proveedor')),
            ],
            options={
                'verbose_name': 'Orden Pedido',
                'verbose_name_plural': 'Ordenes Pedidos',
            },
        ),
    ]
