# Generated by Django 3.1.2 on 2022-05-24 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_minuta_ordenpedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tipo Habitacion',
                'verbose_name_plural': 'Tipo Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.CharField(max_length=20)),
                ('tipo_habita_id_tipo_habita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
