# Generated by Django 3.1.2 on 2022-05-24 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_habitacion_tipohabitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id_promociones', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_promocion', models.CharField(max_length=50)),
                ('desc_promocion', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=40)),
                ('fecha_reserva', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('precio_nro_habi', models.IntegerField(choices=[[0, '1 habitacion - $20.000'], [1, '2 habitacion - $40.000'], [2, '3 habitacion - $60.000'], [3, '4 habitacion - $80.000'], [4, '5 habitacion - $100.000'], [5, '6 habitacion - $120.000']])),
                ('cliente_rut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
                ('id_promocion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.promociones')),
                ('servicio_comedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.minuta')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
