# Generated by Django 3.1.2 on 2022-05-24 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_reserva', models.DateField()),
                ('hora_ingreso', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('reserva_id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.reserva')),
            ],
            options={
                'verbose_name': 'Huesped',
                'verbose_name_plural': 'Huespedes',
            },
        ),
        migrations.CreateModel(
            name='HabitacionReserva',
            fields=[
                ('id_habitacion_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('habitacion_id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.habitacion')),
                ('reserva_id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.reserva')),
            ],
            options={
                'verbose_name': 'Habitacion - Reserva',
                'verbose_name_plural': 'Habitacion - Reserva',
            },
        ),
    ]
