# Generated by Django 3.1.2 on 2022-05-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220525_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='factura',
            name='email_cliente',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
