# Generated by Django 3.1.2 on 2022-06-25 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_huesped_hora_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='telefono',
        ),
    ]
